#!/bin/sh
#
# @file: S99Surfboard
# @brief: Starting/Stopping SurfBoard
#
# @section License
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Copyright (C) 2025 for6to9si@gmail.com. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# @author: for6to9si@gmail.com


ENABLED=yes
DEBUG=true
export PATH=/opt/bin:/opt/sbin:/usr/bin:/bin:/sbin:/usr/sbin
PROCS=surfboard
CONF=/opt/etc/surfboard/conf.json

[ "$DEBUG" = "true" ] && LOG_FILE=/opt/var/log/surfboard/surfboard.log || LOG_FILE=/dev/null

is_running() {
    pgrep -nx "$PROCS" >/dev/null 2>&1
}

case "$1" in
    start)
        echo "Starting $PROCS..."
        echo "=== $(date) === surfboard client info ===" >>"$LOG_FILE"
        $PROCS -c "$CONF" >>"$LOG_FILE" 2>&1 &
        ;;
    stop)
        echo "Stopping $PROCS..."
        killall "$PROCS" >/dev/null 2>&1
        sleep 1
        is_running && killall -9 "$PROCS"
        ;;
    status)
        if is_running; then
            echo "$PROCS is running"
        else
            echo "$PROCS is stopped"
        fi
        ;;
    restart)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        ;;
esac
