name: Go Cross-Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Is this a prerelease?'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build-ipk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - os: linux
            arch: arm64
            output: surfboard-arm64
          - os: linux
            arch: mipsle
            output: surfboard-mipsle
          - os: linux
            arch: amd64
            output: surfboard-amd64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Необходимо для корректной работы git describe

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build for ${{ matrix.target.arch }}
        id: version
        env:
          GOOS: ${{ matrix.target.os }}
          GOARCH: ${{ matrix.target.arch }}
          GOMIPS: softfloat
        run: |
          mkdir -p build
          VERSION=$(grep '^var Version =' main.go | sed -E 's/.*Version = "([^"]+)".*/\1/')
          go build -ldflags "-X main.Version=${VERSION}" -v -o build/${{ matrix.target.output }} .
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Using version: ${VERSION}"

      - name: Verify build output
        run: |
          ls -la build/

      - name: Set up environment
        if: matrix.target.arch != 'amd64'
        run: |
          sudo apt-get update
          sudo apt-get install -y tar gzip jq unzip fakeroot

      - name: Create IPK package structure
        if: matrix.target.arch != 'amd64'
        run: |
          mkdir -p surfboard-${{ matrix.target.arch }}/opt/sbin
          mkdir -p surfboard-${{ matrix.target.arch }}/opt/etc/init.d
          mkdir -p surfboard-${{ matrix.target.arch }}/opt/etc/surfboard
          mkdir -p surfboard-${{ matrix.target.arch }}/opt/etc/surfboard/template
          mkdir -p surfboard-${{ matrix.target.arch }}/opt/var/log/surfboard
          mkdir -p surfboard-${{ matrix.target.arch }}/CONTROL
          
          cp build/${{ matrix.target.output }} surfboard-${{ matrix.target.arch }}/opt/sbin/${{ matrix.target.output }}
          chmod +x surfboard-${{ matrix.target.arch }}/opt/sbin/${{ matrix.target.output }}
          
          cp ./etc/inid.d/S99surfboard surfboard-${{ matrix.target.arch }}/opt/etc/etc/init.d/
          chmod +x surfboard-${{ matrix.target.arch }}/opt/etc/etc/init.d/S99surfboard
          cp ./etc/surfboard/settings.json surfboard-${{ matrix.target.arch }}/opt/etc/surfboard/settings.json
          
          cat > surfboard-${{ matrix.target.arch }}/CONTROL/control <<EOF
          Package: surfboard
          Depends: libc,libssp,librt,libpthread
          Version: ${{ steps.version.outputs.version }}
          Architecture: ${{ matrix.target.arch == 'mipsle' && 'mipsel-3.4' || matrix.target.arch }}
          Section: net
          Description: A minimalistic tool to automate Surfboard setup on Keenetic router systems.
          License: GPL-3.0 license
          Maintainer: for6to9si <for6to9si@gmail.com>
          EOF

      - name: Package IPK
        if: matrix.target.arch != 'amd64'
        run: |
          cd surfboard-${{ matrix.target.arch }}
          fakeroot tar -czf ../data.tar.gz ./opt/sbin ./opt/etc ./opt/var/log/surfboard
          cd ./CONTROL
          fakeroot tar -czf ../../control.tar.gz *
          cd ..
          echo "2.0" > ../debian-binary
          cd ..
          fakeroot tar -czf surfboard-${{ steps.version.outputs.version }}_${{ matrix.target.arch }}.ipk ./debian-binary ./control.tar.gz ./data.tar.gz

      - name: Debug IPK files
        if: matrix.target.arch != 'amd64'
        run: |
          ls -la *.ipk || echo "No .ipk files found"

      - name: Store build timestamp
        if: matrix.target.arch != 'amd64'
        run: echo "BUILD_TIME=$(date +'%T')" >> $GITHUB_ENV

      - name: Deploy using stored timestamp
        if: matrix.target.arch != 'amd64'
        run: echo "Deploying at $BUILD_TIME"

      - name: Upload artifacts
        if: matrix.target.arch != 'amd64'
        uses: actions/upload-artifact@v4
        with:
          name: surfboard-${{ matrix.target.arch }}
          path: ./*.ipk
          if-no-files-found: error

      - name: Set up Docker
        if: matrix.target.arch == 'amd64'
        uses: docker/setup-buildx-action@v3

      - name: Debug working directory
        if: matrix.target.arch == 'amd64'
        run: |
          pwd
          ls -la

      - name: Set TAG_VERSION
        if: matrix.target.arch == 'amd64'
        run: |
          echo "TAG_VERSION=v$(date +%y.%-m.%-d)" >> $GITHUB_ENV

      - name: Log in to DockerHub
        if: matrix.target.arch == 'amd64'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        if: matrix.target.arch == 'amd64'
        run: |
          docker build -t for6to9si/surfboard:latest -t for6to9si/surfboard:${{ env.TAG_VERSION }} --build-arg BINARY_PATH=build/${{ matrix.target.output }} .

      - name: Push Docker Image
        if: matrix.target.arch == 'amd64'
        run: |
          docker push for6to9si/surfboard:latest
          docker push for6to9si/surfboard:${{ env.TAG_VERSION }}

      - name: Upload build artifact
        if: matrix.target.arch == 'amd64'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target.output }}
          path: build/${{ matrix.target.output }}

  deploy-repository:
    runs-on: ubuntu-latest
    needs: [build-ipk]
    permissions:
      contents: write  # Разрешает создание и push тегов/коммитов
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read version from SurfBoard file
        id: generate_tag
        run: |
          VERSION=$(grep '^var Version =' main.go | sed -E 's/.*Version = "([^"]+)".*/\1/')
          TAG_NAME="v$VERSION"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION, Tag: $TAG_NAME"

      - name: Create Git tag and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@github.com"
          TAG_NAME="${{ steps.generate_tag.outputs.tag_name }}"
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists, skipping."
          else
            git tag "$TAG_NAME"
            git push origin "$TAG_NAME"
          fi

      - name: Clean workspace
        run: |
          rm -rf artifacts/*

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Debug artifact directory
        run: |
          ls -R artifacts/

      - name: Debug github.ref_name and file pattern
        run: |
          echo "steps.generate_tag.outputs.tag_name: ${{ steps.generate_tag.outputs.tag_name}}"
          find artifacts/ -name "surfboard-*.ipk"

      - name: Create release and upload artifacts (signed)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${{ steps.generate_tag.outputs.tag_name }}
          PRERELEASE=${{ github.event.inputs.prerelease || 'true' }}

          # Найдём предыдущий тег по дате создания
          PREV_TAG=$(git tag --sort=-creatordate | grep -v "^${TAG}$" | head -n 1 || echo "")

          if [ -z "$PREV_TAG" ]; then
            echo "No previous tag found. Logging all history."
            git log --pretty=format:'- [%h](https://github.com/${{ github.repository }}/commit/%H): %s' > changelog.txt
          else
            echo "Generating changelog from $PREV_TAG to HEAD"
            git log "$PREV_TAG"..HEAD --pretty=format:'- [%h](https://github.com/${{ github.repository }}/commit/%H): %s' > changelog.txt
          fi

          echo "Changelog:"
          cat changelog.txt

          if [ "$PRERELEASE" = "true" ]; then
            gh release create "$TAG" artifacts/surfboard-*/surfboard-*.ipk \
              --repo "$GITHUB_REPOSITORY" \
              --title "Release $TAG" \
              --notes-file changelog.txt \
              --prerelease
          else
            gh release create "$TAG" artifacts/surfboard-*/surfboard-*.ipk \
              --repo "$GITHUB_REPOSITORY" \
              --title "Release $TAG" \
              --notes-file changelog.txt 
          fi
